version: 2

multi-ecosystem-groups:
  vcpkg-and-submodule:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "vcpkg"
    directory: "/"
    multi-ecosystem-group: "vcpkg-and-submodule"
    patterns:
      - "*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    multi-ecosystem-group: "vcpkg-and-submodule"
    patterns:
      - "*"
